version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce2-api
    ports:
        - "6895:50"
    environment:
        - ConnectionStrings__DefaultConnection=Server=db;Database=EcommerceDB;User=sa;Password=P@ssw0rd;TrustServerCertificate=true
    networks:
        - ecommerce-net

networks:
  ecommerce-net:
    external: true